### ISSUE TITLE
Early issues

### ISSUE THREAD

**Issue by hayd** [hayd/deno-udd#1]
- [x] Add --help
- [x] exit with code 1 if not args passed
- [x] only show test stdout+stderr if the test fails (?)
- [x] show number [1/N] on output for each url that's being updated
- [x] cache the owner/repo versions (so it's not re-requested if multiple std urls are used) 
- [x] make output more concise
- [ ] use logger and support -q and -v verbosity flags
- [x] tests for update.ts
- [ ] add more registries e.g. raw.github

---

Future: interactive (choose which version, retry/continue etc.), semver handling, lock creation, custom domains (pass ts file that export defaults your own Registry/Versioned class and udd dynamically imports it and appends it to IMPLS/REGISTRIES), more flags...

**Comment by zekth** [comment]
A suggestion would be to add `dry run` for CI for example?

**Comment by hayd** [comment]
@zekth What would dry run look like compared to the existing --test?

**Comment by zekth** [comment]
so i'd like to do something like 
```
udd *.ts --dry-run
# outputs
mod.ts:
-- export { decode } from "https://deno.land/std@v0.34.0/strings/decode.ts";
++ export { decode } from "https://deno.land/std@v0.35.0/strings/decode.ts";
```
And if change is detected it exits with `1` otherwise with `0`.

**Comment by hayd** [comment]
Ooh, the diff is a nice way to render. I might initially just do a faux diff of just the urls until proper parsing of import statements... Or is there an existing deno diff?

console.table might be nice for output and a progress bar will be nice.

Not sure about the exit code part... feels like a --check (implies --dry-run)

Unfortunately semver lib isn't strict, around 80 issues... But definitely want to make use of it.

**Comment by hayd** [comment]
@zekth released 0.0.3 (with dry-run but a slightly different output)

**Comment by hayd** [comment]
@zekth did you ever see the [semantic versioning](https://github.com/hayd/deno-udd/blob/master/README.md#semantic-versioning)?
I'm interested in feedback!... I added a [note on the README](https://github.com/hayd/deno-udd#update-deno-dependencies) but I suspect/worry it is confusing.

**Comment by zekth** [comment]
@hayd looks ok to me, at least may need an example otherwise it's ok to me

**Comment by hayd** [comment]
@zekth Good call, https://github.com/hayd/deno-udd#examples, thanks!
