### ISSUE TITLE
confusion with std and deno releases

### ISSUE THREAD

**Issue by hayd** [hayd/deno-udd#11]
With the new std/deno release cycles this needs to be supported.

cc @lucacasonato (FYI it's broken at the moment)

latest std is 0.50.0 but udd wants to use v1.0.0-rc2

**Comment by lucacasonato** [comment]
I’ll look into it.

**Comment by hayd** [comment]
I think it needs this list to be only ones those releases prefixed with `std/`:

https://github.com/hayd/deno-udd/blob/94d0cdaf7a8a21fca9853ac124b2d28b417ee2b6/registry.ts#L146

I will get to in next couple of days if you don't beat me to it.
