### ISSUE TITLE
Add jsdelivr.net to supported module hosts

### ISSUE THREAD

**Issue by shah** [hayd/deno-udd#18]
Great lib! We use https://cdn.jsdelivr.net/gh/{githubURL} for grabbing our modules. Would you mind adding that as a supported host?

**Comment by shah** [comment]
I've switched over to using `denopkg.com` so this is no longer required. My `udd` needs are now met! Thanks for putting together this library, saves a lot of time. :+1:

**Comment by hayd** [comment]
I think I'll leave this open - it shouldn't be too hard to implement. 👍
