### ISSUE TITLE
Warning using std versions prefixed with "v"

### ISSUE THREAD

**Issue by oscarotero** [hayd/deno-udd#27]
Hi.
I see this tool prefixes the deno std packages version with a "v", so for example, this:

```js
import { dirname } from "https://deno.land/std@0.71.0/path/mod.ts";
```

is converted to this:

```js
import { dirname } from "https://deno.land/std@v0.71.0/path/mod.ts";
```

After the update, I'm getting the following error:

> Warning std versions prefixed with 'v' will be deprecated on October 1st 2020. Please change your import to https://deno.land/std@0.71.0/path/mod.ts (at https://deno.land/std@v0.71.0/path/mod.ts)

I suggest to change this before it's deprecated.

**Comment by rclarey** [comment]
@oscarotero This will be fixed when #25 is merged
