### ISSUE TITLE
Ignore some deps

### ISSUE THREAD

**Issue by RivierGrullon** [hayd/deno-udd#33]
Is there a way to ignore a dep that I don't want to update.

there are some packages that use some versions that some functions no longer exist in new versions include your own deps like encode and decode from deps.ts

It would like this a way to ignore 

```javascript

//udd-ignore
export { decode, encode } from "https://deno.land/std@0.80.0/encoding/utf8.ts";
```

**Comment by hayd** [comment]
you can add `#=` as the fragment see https://github.com/hayd/deno-udd#semantic-versioning 

e.g. ```export { decode, encode } from "https://deno.land/std@0.80.0/encoding/utf8.ts#=";```

**Comment by RivierGrullon** [comment]
😮 well in that case nice 👍🏼, but I think you should add this in that line, when I update all the dependencies from udd, It brokes b because in the newest version of encoding the utf8.ts does not exist

**Comment by RivierGrullon** [comment]
btw thank you for the fast reply :)

**Comment by hayd** [comment]
> but I think you should add this in that line

yeah, looking at the README it _is_ a little cryptic!
