### ISSUE TITLE
Breaks on Deno 1.13

### ISSUE THREAD

**Issue by talentlessguy** [hayd/deno-udd#35]
```
➜ udd ./**/*.ts
error: Found argument '--allow-plugin' which wasn't expected, or isn't valid in this context
        Did you mean --allow-run?

USAGE:
    deno run <SCRIPT_ARG>... --allow-env=<allow-env> --allow-net=<allow-net> --allow-read=<allow-read> --allow-run=<allow-run> --allow-write=<allow-write>

For more information try --help
```

**Comment by talentlessguy** [comment]
nvm I upgraded to `udd` latest and it worked

**Comment by shah** [comment]
Same here, it was broken for me in 1.13 and then I upgraded to 0.5.0 and I'm back in business. UDD is a fantastic tool!

**Comment by Shougo** [comment]
Oh, udd 0.5.0 works with deno 1.13.
I think the compatibility problem should be documented in README.

**Comment by hayd** [comment]
The relevant deno bug: https://github.com/denoland/deno/issues/11819
(Though it may not be fixed 🤷 )

I'm going to pin this issue for the moment so other users have something to find if they tripped here.

**Comment by hayd** [comment]
It's unclear if this may happen again, as not fixed in Deno itself (I don't think).

But closing since if this happens again in future the solution is to use `udd --upgrade` (in 0.6.0+).
