### ISSUE TITLE
self-upgrade command like Velociraptor

### ISSUE THREAD

**Issue by mikanIchinose** [hayd/deno-udd#44]
[Velociraptor has self-upgrade command](https://velociraptor.run/docs/installation/#upgrading) like this.

```
vr upgrade
```

So I'd like to have udd-upgrade command.

```
udd upgrade
```

**Comment by hayd** [comment]
See:

https://github.com/jurassiscripts/velociraptor/blob/971b7db71cf635b0c8f2de822aa4270e52cce498/src/cli/commands/upgrade.ts#L28-L35

Shelling out seems pretty reasonable strategy, though IMO [`execPath`](https://github.com/lumeland/lume/blob/d1ae569e09c489b4328a7b504e7fb2b44b57da31/install.ts#L22) is preferable. 

However I suspect for udd this option makes more sense as `udd --upgrade` (like [`--help`](https://github.com/hayd/deno-udd/blob/5e548f82a26bfde8a5e06425a3becd4c4d2a12b6/main.ts#L47-L51) ).

**Comment by hayd** [comment]
Thanks for the idea/feedback @mikanIchinose . This is released in 0.6.0 !

**Comment by mikanIchinose** [comment]
sound good!! 👍🏻
