### ISSUE TITLE
deno 1.18.0: a config file in cwd can cause udd to error

### ISSUE THREAD

**Issue by UltiRequiem** [hayd/deno-udd#59]
https://github.com/hayd/deno-udd#scheduled-github-action

Since 5 days ago, the day the version `0.7.1` was released, my CI stopped working:

https://github.com/UltiRequiem/timero/actions/workflows/udd.yaml

`error: TS2304 [ERROR]: Cannot find name 'Deno'.`

**Comment by hayd** [comment]
Oh no! Sorry about that. Note: This was also the day 1.18.0 was released (I released that day because udd bumped the std dependencies), and so also the day CI upgraded you to that.

That is a confusing error... and more bizarrely I can't seem to replicate it on udd itself (udd.yaml is working fine for me on 1.17.3 and [1.18.0](https://github.com/hayd/deno-udd/runs/4932668513?check_suite_focus=true)).

On cloning your repository this definitely seems to be a deno 1.18.0 issue... !!

```
❱ deno upgrade --version 1.17.3
Checking https://github.com/denoland/deno/releases/download/v1.17.3/deno-aarch64-apple-darwin.zip
28.6 MiB / 28.6 MiB (100.0%)
Deno is upgrading to version 1.17.3
Archive:  /var/folders/3h/n7z477gs1yz9hhvnv5h0mbfc0000gn/T/.tmpiG9nL4/deno.zip
  inflating: deno
Upgraded successfully
❱ deno --version
deno 1.17.3 (release, aarch64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
❱ deno run -A ../deno-udd/main.ts deps.ts
deps.ts
[2/2] Using latest: https://deno.land/x/timezones@v1.0.0/mod.js
Already latest version:
https://deno.land/x/fuse@v6.4.1/dist/fuse.esm.js == v6.4.1
https://deno.land/x/timezones@v1.0.0/mod.js == v1.0.0
❱ deno upgrade --version 1.18.0
Checking https://github.com/denoland/deno/releases/download/v1.18.0/deno-aarch64-apple-darwin.zip
27.7 MiB / 27.7 MiB (100.0%)
Deno is upgrading to version 1.18.0
Archive:  /var/folders/3h/n7z477gs1yz9hhvnv5h0mbfc0000gn/T/.tmpJleF4S/deno.zip
  inflating: deno
Upgraded successfully
❱ deno --version
deno 1.18.0 (release, aarch64-apple-darwin)
v8 9.8.177.6
typescript 4.5.2
❱ deno run -A ../deno-udd/main.ts deps.ts
Check file:///REDACTED/deno-udd/main.ts
error: TS2304 [ERROR]: Cannot find name 'Deno'.
const { noColor } = Deno;
...
```
❗

**Comment by hayd** [comment]
This is due to the deno.json (in 1.18.0 this is auto-looked up in the directory you're in).

**Comment by hayd** [comment]
Is the solution to pass the config explicitly as deno.land/x/udd/deno.json (does that even work)?
Surely this must be affecting many CLIs! 😢

**Comment by UltiRequiem** [comment]
As a temporal solution, you can delete the `deno.json` file in the  CI, like in

https://github.com/UltiRequiem/timero/commit/56dc4ba0b64f7deb19607d4b476be88279fcd6ac

**Comment by UltiRequiem** [comment]
This is fixed thanks to https://github.com/denoland/deno/issues/13744 🚀
