### ISSUE TITLE
unpkg (et al?) must have non-zero directory

### ISSUE THREAD

**Issue by hayd** [hayd/deno-udd#6]
Currently udd does this which is wrong:

```diff
-// https://unpkg.com/@types/jszip@3.1.7/index.d.ts
+// https://unpkg.com/@undefined/jszip@3.1.7/index.d.ts
```

**Comment by takker99** [comment]
I fixed this bug like the commit (https://github.com/takker99/deno-udd/commit/b083636325353198f6f0e98734c3b5327a622a10).
Though all tests are passed, I'm not sure this coding is nice. This seems like boilerplate a bit...

Would you mind If I opened the pull request?
